name: Checkov security test
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.tf"
      - ".github/workflows/checkov.yml"

permissions:
  contents: read

jobs:
  checkov_security:
    name: Checkov security tests
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      checks: write
      security-events: write
      actions: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: prepare reports dir
        run: mkdir --parents ${{runner.temp}}/reports_sast_terraform/

      - name: install checkov
        run: |
          pip3 install --upgrade checkov
          echo $PATH
          checkov --version
          which checkov

      - name: generate json report
        run: >
          checkov
          --config-file .config/sast_terraform_checkov_json.yml
          --directory .
          --output cli
          --output json
          --output sarif
          --output-file-path console,checkov-terraform-results.json,checkov-terraform-results.sarif
