name: Terraform tests
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read

jobs:
  terraform_validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Terraform setup
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.12.2

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Terraform format
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ./examples/default
        run: terraform init -get -backend=false

      - name: Terraform validate
        working-directory: ./examples/default
        run: terraform validate
