name: Terraform tests
on:
  workflow_dispatch:
  push:
    paths:
      - "**/*.tf"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read

jobs:
  terraform_validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Terraform setup
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: 1.6.1

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Terraform format
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ./examples/default
        run: terraform init -get -backend=false

      - name: Terraform validate
        working-directory: ./examples/default
        run: terraform validate
